language: python

python:
  - '3.6'

env:
  - FLASK_ENV='testing'

install:
  - pip install -r requirements.txt
  - pip install coveralls codecov
  - pip install pytest

services:
  - postgresql

before_script:
  - psql -c 'create database politico_db;' -U postgres
  - psql -c 'create database test_politico_db;' -U postgres


script:
  - pytest --cov=app/


after_success:
  - coveralls